version: '3'

services:
  nginx-proxy:
    container_name: nginx
    image: jwilder/nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  db:
    container_name: postgresql
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
    depends_on:
      - nginx-proxy

  web:
    container_name: mechhead-web
    build: '.'
    command: rails s -p 3000 -b 0.0.0.0
    volumes:
      - .:/mechhead
    ports:
      - '3000:3000'
    environment:
      VIRTUAL_HOST: mechhead.test
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - nginx-proxy
      - db

volumes:
  postgres-data:
